import type { Question } from './data'

const RESERVED = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'enum',
  'implements',
  'interface',
  'let',
  'package',
  'private',
  'protected',
  'public',
  'static',
  'yield',
])

function escapeJsdocLine(s: string): string {
  return s.replace(/\*\//g, '* /').replace(/^\s*\*\s?/gm, '* ')
}

/** Infer a stable function name from the title (e.g. "Implement debounce(...)") or fall back to question id. */
export function extractMockFunctionName(title: string, id: string): string {
  const backtick = title.match(/`([a-zA-Z0-9_]+)`/)
  if (backtick) {
    const n = backtick[1]
    return RESERVED.has(n) ? `${n}_fn` : n
  }
  const implement = title.match(/^Implement\s+`?([a-zA-Z0-9_]+)`?/i)
  if (implement) {
    const n = implement[1]
    return RESERVED.has(n) ? `${n}_fn` : n
  }
  let slug = id.replace(/[^a-zA-Z0-9_]/g, '_')
  if (/^\d/.test(slug)) slug = `_${slug}`
  if (!slug) slug = 'solution'
  if (RESERVED.has(slug)) return `${slug}_fn`
  return slug
}

function pascalCase(name: string): string {
  const parts = name.split(/[^a-zA-Z0-9]+/).filter(Boolean)
  if (parts.length === 0) return 'Solution'
  return parts.map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join('')
}

/** Safe basename for a virtual interview source file (Monaco model URI). */
export function questionCodeFileBase(id: string): string {
  let s = id.replace(/[^a-zA-Z0-9_-]/g, '_').replace(/_+/g, '_')
  if (/^\d/.test(s)) s = `_${s}`
  return s || 'solution'
}

export function questionTsFileName(q: Question): string {
  return `${questionCodeFileBase(q.id)}.ts`
}

/** React component-building cards (`react-build-*`) use live Sandpack preview (react-ts). */
export function questionUsesReactSandpackPreview(q: Question): boolean {
  return q.id.startsWith('react-build-')
}

/** Virtual filename for the mock editor (Monaco URI tab) — `.tsx` for React preview questions. */
export function questionEditorFileName(q: Question): string {
  return questionUsesReactSandpackPreview(q)
    ? `${questionCodeFileBase(q.id)}.tsx`
    : questionTsFileName(q)
}

/**
 * Ambient declarations for this card — completions for INTERVIEW_PROBLEM.* in the editor.
 */
export function buildQuestionAmbientTypes(q: Question): string {
  return `
/** Typed metadata for the active interview question (autogenerated). */
declare const INTERVIEW_PROBLEM: {
  readonly id: ${JSON.stringify(q.id)}
  readonly title: ${JSON.stringify(q.title)}
  readonly category: ${JSON.stringify(q.category)}
  readonly difficulty: ${JSON.stringify(q.difficulty)}
  readonly description: ${JSON.stringify(q.description)}
}
`
}

/**
 * Initial VS Code buffer for mock code review: problem text in JSDoc, a types interface, and a function stub.
 */
export function buildMockCodeReviewStarter(q: Question): string {
  const fnName = extractMockFunctionName(q.title, q.id)
  const typesName = `${pascalCase(fnName)}Types`

  const title = escapeJsdocLine(q.title.trim())
  const descLines = q.description
    .trim()
    .split('\n')
    .map((line) => ` * ${escapeJsdocLine(line)}`)
    .join('\n')

  return `/**
 * ${title}
 *
${descLines}
 *
 * ${q.category} · ${q.difficulty}
 *
 * Tip: \`INTERVIEW_PROBLEM\` is typed from this question (see completions).
 */

/** Shape the data / API for this problem — refine to match the prompt. */
interface ${typesName} {
  // e.g. argument types, return type helpers, nested structures
}

function ${fnName}(/* parameters — align with ${typesName} and the problem above */): unknown {
  // Your implementation
  // Example (this file is ${questionTsFileName(q)}):
  // return INTERVIEW_PROBLEM.title
}
`
}

/**
 * Starter for React component mock questions — visible preview placeholder, `App` export for Sandpack wrapper.
 */
export function buildMockReactComponentStarter(q: Question): string {
  const title = escapeJsdocLine(q.title.trim())
  const descLines = q.description
    .trim()
    .split('\n')
    .map((line) => ` * ${escapeJsdocLine(line)}`)
    .join('\n')

  return `/**
 * ${title}
 *
${descLines}
 *
 * ${q.category} · ${q.difficulty}
 *
 * Export a named component as \`App\`, \`Preview\`, or \`Demo\` so the live preview can mount it.
 */

export function App() {
  return (
    <section style={{ padding: 16, fontFamily: 'system-ui, sans-serif' }}>
      <p style={{ margin: 0, color: '#94a3b8' }}>Live preview — replace with your solution.</p>
    </section>
  )
}
`
}

/** Initial editor buffer: React component starter or classic function / types stub. */
export function buildMockCodeEditorStarter(q: Question): string {
  if (questionUsesReactSandpackPreview(q)) {
    return buildMockReactComponentStarter(q)
  }
  return buildMockCodeReviewStarter(q)
}
